spring:
  datasource:
    username:
    password:
    url:
  redis:
    host:
    port:

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml



#sa-Token配置
sa-token:
  token-name: satoken
# token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
# token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
# 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
# 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
# token风格
  token-style: uuid
# 是否输出操作日志
  is-log: false

#跨域配置
cors:
  allowedHeader: '*'
  allowedOrigins: http://localhost:3000

arithmetic:
  sys-conf:
    front-end-url: localhost
    mail-sender:
    enable-mail-register: true
    maxAvatarSizeM: 5
  mail:
    enable-stable: true
    task-queue-length: 15
    mailList:
      - host: smtp.qq.com
        username:
        password: